-- MySQL Script generated by MySQL Workbench
-- Mon Jul  7 16:45:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ispw
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ispw` ;

-- -----------------------------------------------------
-- Schema ispw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ispw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ispw` ;

-- -----------------------------------------------------
-- Table `ispw`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`users` ;

CREATE TABLE IF NOT EXISTS `ispw`.`users` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('CLIENT', 'TRAINER') NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`trainer` ;

CREATE TABLE IF NOT EXISTS `ispw`.`trainer` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `online` TINYINT NULL DEFAULT NULL,
  `birthDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `mail`
    FOREIGN KEY (`email`)
    REFERENCES `ispw`.`users` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`course` ;

CREATE TABLE IF NOT EXISTS `ispw`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `remaining` INT NULL DEFAULT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  `level` VARCHAR(45) NULL DEFAULT NULL,
  `trainer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pt_idx` (`trainer` ASC) VISIBLE,
  CONSTRAINT `pt`
    FOREIGN KEY (`trainer`)
    REFERENCES `ispw`.`trainer` (`email`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`subscription` ;

CREATE TABLE IF NOT EXISTS `ispw`.`subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `type` ENUM('ANNUALE', 'MENSILE', 'TRIMESTRALE', 'QUADRIMESTRALE') NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `discount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`customer` ;

CREATE TABLE IF NOT EXISTS `ispw`.`customer` (
  `mail` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `online` TINYINT NULL DEFAULT NULL,
  `subscription` INT NULL DEFAULT NULL,
  `injury` VARCHAR(45) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`mail`),
  INDEX `subscription_idx` (`subscription` ASC, `mail` ASC) VISIBLE,
  CONSTRAINT `customermail`
    FOREIGN KEY (`mail`)
    REFERENCES `ispw`.`users` (`email`),
  CONSTRAINT `subscription`
    FOREIGN KEY (`subscription`)
    REFERENCES `ispw`.`subscription` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`exercise` ;

CREATE TABLE IF NOT EXISTS `ispw`.`exercise` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `numberSeries` INT NULL DEFAULT NULL,
  `numberReps` INT NULL DEFAULT NULL,
  `restTime` ENUM('30', '60', '90', '120') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`specialization` ;

CREATE TABLE IF NOT EXISTS `ispw`.`specialization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`expertieses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`expertieses` ;

CREATE TABLE IF NOT EXISTS `ispw`.`expertieses` (
  `specialization` INT NOT NULL,
  `trainer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`specialization`, `trainer`),
  INDEX `trainer_idx` (`trainer` ASC) VISIBLE,
  CONSTRAINT `specialization`
    FOREIGN KEY (`specialization`)
    REFERENCES `ispw`.`specialization` (`id`),
  CONSTRAINT `train`
    FOREIGN KEY (`trainer`)
    REFERENCES `ispw`.`trainer` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`schedule` ;

CREATE TABLE IF NOT EXISTS `ispw`.`schedule` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `customer` VARCHAR(45) NULL DEFAULT NULL,
  `trainer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_idx` (`customer` ASC) VISIBLE,
  INDEX `trainer_idx` (`trainer` ASC) VISIBLE,
  CONSTRAINT `customer`
    FOREIGN KEY (`customer`)
    REFERENCES `ispw`.`customer` (`mail`),
  CONSTRAINT `trainer`
    FOREIGN KEY (`trainer`)
    REFERENCES `ispw`.`trainer` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`participation` ;

CREATE TABLE IF NOT EXISTS `ispw`.`participation` (
  `schedule` INT NOT NULL,
  `exercise` INT NOT NULL,
  PRIMARY KEY (`schedule`, `exercise`),
  INDEX `exercise_idx` (`exercise` ASC) VISIBLE,
  CONSTRAINT `exercise`
    FOREIGN KEY (`exercise`)
    REFERENCES `ispw`.`exercise` (`id`),
  CONSTRAINT `scheda`
    FOREIGN KEY (`schedule`)
    REFERENCES `ispw`.`schedule` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`pending`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`pending` ;

CREATE TABLE IF NOT EXISTS `ispw`.`pending` (
  `customer` VARCHAR(45) NOT NULL,
  `course` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `hour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer`, `course`, `hour`, `date`),
  INDEX `coursep_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `coursep`
    FOREIGN KEY (`course`)
    REFERENCES `ispw`.`course` (`id`),
  CONSTRAINT `customerp`
    FOREIGN KEY (`customer`)
    REFERENCES `ispw`.`customer` (`mail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`request` ;

CREATE TABLE IF NOT EXISTS `ispw`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule` INT NULL DEFAULT NULL,
  `exercise` INT NULL DEFAULT NULL,
  `reason` VARCHAR(45) NULL DEFAULT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `richiestaesercizio_idx` (`exercise` ASC) VISIBLE,
  INDEX `richiestascheda_idx` (`schedule` ASC) VISIBLE,
  CONSTRAINT `richiestaesercizio`
    FOREIGN KEY (`exercise`)
    REFERENCES `ispw`.`exercise` (`id`),
  CONSTRAINT `richiestascheda`
    FOREIGN KEY (`schedule`)
    REFERENCES `ispw`.`schedule` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`reservation` ;

CREATE TABLE IF NOT EXISTS `ispw`.`reservation` (
  `customer` VARCHAR(45) NOT NULL,
  `course` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `hour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer`, `course`, `date`, `hour`),
  INDEX `corso_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`customer`)
    REFERENCES `ispw`.`customer` (`mail`),
  CONSTRAINT `corso`
    FOREIGN KEY (`course`)
    REFERENCES `ispw`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ispw`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ispw`.`session` ;

CREATE TABLE IF NOT EXISTS `ispw`.`session` (
  `day` VARCHAR(45) NOT NULL,
  `hour` VARCHAR(45) NOT NULL,
  `course` INT NULL DEFAULT NULL,
  PRIMARY KEY (`day`, `hour`),
  INDEX `session_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `session`
    FOREIGN KEY (`course`)
    REFERENCES `ispw`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
